url = "tourism_service"

level = "debug"
logEncoding = "console"

nameDB = "tourism_db"
hostDB =  "localhost"
portDB = "5342"
usesrDB = "user"
passwordDB = "user"

hostHttpServer = "localhost"
portHttpServe = "8080"